version: '3.8'

services:
  email-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_RETRY_ATTEMPTS=3
      - INITIAL_RETRY_DELAY=1000
      - MAX_RETRY_DELAY=10000
      - RETRY_BACKOFF_MULTIPLIER=2
      - RATE_LIMIT_MAX_REQUESTS=10
      - RATE_LIMIT_TIME_WINDOW=60000
      - CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
      - CIRCUIT_BREAKER_RECOVERY_TIMEOUT=30000
      - CIRCUIT_BREAKER_MONITORING_PERIOD=60000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped 